version: "3.9"  # optional since v1.27.0
services:
  blazar:
    container_name: blazar-backend
    build: .
    ports:
      - "8080:8080"
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    command: nodemon --watch views -e ts,js,html src/index.ts
#    links: