version: "3.4"  # optional since v1.27.0
services:
  blazar:
    container_name: blazar-backend
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    command: npm run dev